#!/bin/bash -x

# file: install.sh
# author: Josue Teodoro Moreira <teodoro.josue@protonmail.ch>
# date: Jul 16, 2021

# check os
os=$(uname)
if ! [[ ${os} == 'Linux' ]]
then
  echo '${os} not supported.'

  exit 0
fi

dotfiles_dir=$(pwd)
 
echo 'Installing base'
 
# basic
basic=base-devel git vim emacs curl wget
sudo pacman -S ${basic}
 
# xorg
x=xorg xorg-drivers xorg-fonts xorg-xinit xorg-apps
sudo pacman -S $x
 
# window manager and visual stuff
wm=i3 dunst alacritty
fonts=ttf-dejavu ttf-font-awesome ttf-hack ttf-iosevka-nerd
sudo pacman -S ${wm}
sudo pacman -S ${fonts}
 
# audio stuff
audio=alsa pulseaudio-alsa alsa-utils alsa-tools pavucontrol mpv
sudo pacman -S ${audio}
pulseaudio -D
 
# install aur
cd ~/
git clone https:///aur.archlinux.org/yay.git
cd ./yay
makepkg -si
 
# yay stuff
yay_stuff=paperview-git nightshift
yay -S ${yay_stuff}
 
# copy files
cd ${dotfiles_dir}
 
# xorg
sudo mkdir -p /etc/X11/xorg.conf.d/
cp ./xorg/*.conf /etc/X11/xorg.conf.d/
cp ./xorg/.xinitrc ~/.xinitrc
 
# vim
cp ./vim/.vimrc ~/.vimrc
 
# emacs
mkdir -p ~/.emacs.d/
cp ./emacs/init.el ~/.emacs.d/init.el
 
# i3
mkdir -p ~/.config/i3/
cp ./i3/* ~/.config/i3/
 
# i3blocks
mkdir -p ~/.config/i3blocks/
cp ./i3blocks/* ~/.config/i3blocks/
 
# i3status
mkdir -p ~/.config/i3status
cp ./i3status/* ~/.config/i3status/
 
# alacritty
mkdir -p ~/.config/alacritty/
cp ./alacritty/* ~/.config/alacritty/
 
# wallpaper
mkdir -p ~/Pictures/wallpaper/
cp ./wallpaper/* ~/Pictures/wallpaper/
